version: "3.4"

services:
    taskvault.api:
        build:
          context: .
          dockerfile: src/TaskVault.API/Dockerfile
        ports:
          - "8080:80"
        depends_on:
          - db
          - taskvault.summaryapi
        networks:
          - mynetwork

    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1433:1433"
        environment:
            SA_PASSWORD: "S3cur3P@ssW0rd!"
            ACCEPT_EULA: "Y"
        networks:
          - mynetwork

    taskvault.summaryapi:
        build:
            context: .
            dockerfile: src/TaskVault.SummaryAPI/Dockerfile
        ports:
            - "8090:80"
        networks:
          - mynetwork

networks:
    mynetwork: