// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskVault.Infrastructure.Data;

#nullable disable

namespace TaskVault.Infrastructure.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20231022163040_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskVault.Domain.Auth", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Roles")
                        .HasColumnType("int");

                    b.Property<Guid>("Salt")
                        .HasMaxLength(1000)
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Salt")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Auth", "Auth");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Password = "L4DYwGl7p4dvA4xKMRrhE1aMywSN0LYEOJ0jd5nelZzf/PZjfVVg607JRjDgQjFmkF9gGR7Zsc7LUNaaHMplDne351ErT/EJZn6/KcVEbOUXb9qY+SOgs34HT6zTKs3jj4siCZkpOqY5VE5O+SFMSNbAp2iZK1L9xX5ER6Ibs1CgWCgsQghTdjAtF9JjFO8FhXfDMeLdwLz3TSlsKEwNaMdp5s6gzYoxbHrq33SVLD/pOy7OxsjlNCKXK3LqzaICYppNKq8y5Pgu0RI/lGFIezV0hTkY/np6+VzAimSsUUgbZiNez7ook9FSyGZwW4NEfYERMe0O5amb2jiDV9G0cAUhMuQdRJj5rDgTo55WEwSb9r9h99q323GVVLg8zjfj0acThxIK/ZHSocpc/NgoIGEksR1TMEOXZNr6O79C9/FPNi6HME44MI1+dGYKXqnYc6DpccrATtcNuTJ/B5Ouowh25ZmKZuupmPuVTU+dbZmEcGPuaITUD5Fd2k4sVISOy2HhlyK9vv4q/LsCZqa1OP9fEalWBx/1uuUMY0lG39gG4JVgoWKWAvcINDaEmUbhINqKCLkj8353Z7wdI1PHILP4Yqj6H27S2c1eB7NfAIpakaG72wBPGNzXG9XpAJBz622JBCrP2wxTDERUKe9/y512DMpfvbg9xJKNWFq3Bkw=",
                            Roles = 3,
                            Salt = new Guid("3340f9d5-cba1-4fa8-b0ea-a28c4f974ae7"),
                            UserId = 1L,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("TaskVault.Domain.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Progress")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Item", "Item");
                });

            modelBuilder.Entity("TaskVault.Domain.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User", "User");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "administrator@administrator.com",
                            Name = "Administrator",
                            Status = 1
                        });
                });

            modelBuilder.Entity("TaskVault.Domain.Auth", b =>
                {
                    b.HasOne("TaskVault.Domain.User", "User")
                        .WithOne()
                        .HasForeignKey("TaskVault.Domain.Auth", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
